server {
    listen 0.0.0.0:580;
    server_name localhost;
    root /var/www/app/static;

    location /assets {
        alias /var/www/app/static/assets/;
	autoindex on;
    }

    location /hidden {
        deny all;
    }

    location /backup {
        alias /var/www/app/static/backup/;
        autoindex on;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
